name: flutter_base_clean_getx_app
description: Flutter Base App with Clean GetX
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #State Manager
  get: ^4.6.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #Dependency Injection
  get_it: ^7.6.4

  #Code Generator
  freezed: ^2.3.2

  #Tools
  dartz: ^0.10.1
  json_annotation: ^4.8.1

  #File
  open_file_plus: ^3.4.1
  flutter_file_dialog: ^3.0.2
  path_provider: ^2.0.12

  #Device Related and Resources
  permission_handler: ^10.2.0
  mobile_number: ^2.1.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  flutter_contacts: ^1.1.7+1
  camera: ^0.10.5+7

  #Remote and Connection
  dio: ^5.3.2
  html: ^0.15.0
  #http: ^0.13.5
  connectivity_plus: ^5.0.2
  internet_connection_checker_plus: ^2.1.0
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0

  #Storage
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1

  #UI
  flutter_animate: ^4.1.0

  #Text and Text-Field
  auto_size_text: ^3.0.0
  mask_text_input_formatter: ^2.7.0

  #Widget
  loading_animation_widget: ^1.2.0+4

  #Localization
  intl: ^0.18.1
  timezone: ^0.8.0

  #Docs
  dartdoc: ^6.3.0

  #Sharing
  share_plus: ^7.2.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Code Generator
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  freezed_annotation: ^2.2.0
  injectable_generator: ^2.4.1

  #Test
  build_test: ^2.1.6
  build_web_compilers: ^3.2.7
  responsive_framework: ^0.2.0

  #Icon
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter:
  generate: true

flutter_intl:
  enabled: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf