name: flutter_base_clean_getx_app
description: Flutter Base App with Clean GetX
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #State Manager
  get: ^4.6.6
  #bloc: ^8.1.4
  #flutter_bloc: ^8.1.5

  #Dependency Injection
  #get_it: ^7.6.7

  #Code Generator
  freezed: ^2.4.7

  #Tools
  dartz: ^0.10.1
  json_annotation: ^4.8.1

  #File
  open_file_plus: ^3.4.1+1
  flutter_file_dialog: ^3.0.2
  path_provider: ^2.1.2

  #Device Related and Resources
  permission_handler: ^10.4.5
  #permission_handler_web: ^0.0.2
  mobile_number: ^2.1.1
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  flutter_contacts: ^1.1.7+1
  camera: ^0.10.5+9

  #Remote and Connection
  dio: ^5.4.2+1
  html: ^0.15.4
  #http: ^1.2.1
  #curl_logger_dio_interceptor: ^1.0.0
  connectivity_plus: ^5.0.0
  internet_connection_checker_plus: ^2.2.0
  url_launcher: ^6.2.5
  url_strategy: ^0.2.0

  #Storage
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1

  #UI
  flutter_animate: ^4.5.0

  #Text and Text-Field
  auto_size_text: ^3.0.0
  mask_text_input_formatter: ^2.9.0

  #Widget
  loading_animation_widget: ^1.2.1

  #Localization
  intl: ^0.18.1
  timezone: ^0.9.2
  #flutter_timezone: ^1.0.8
  persian_datetime_picker: ^2.6.0

  #Docs
  dartdoc: ^6.3.0

  #Sharing
  share_plus: ^7.2.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Code Generator
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.2.0

  #Test
  build_test: ^2.2.2
  build_web_compilers: ^4.0.10
  responsive_framework: ^1.4.0

  #Icon
  flutter_launcher_icons: ^0.13.1

  #Lints
  flutter_lints: ^3.0.2
  lint: ^2.3.0
  lints: ^3.0.0

flutter_intl:
  enabled: true

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf